### ISSUE TITLE
Update package.json for minimum nodejs version

### ISSUE THREAD

**Issue by rocky** [ConsenSys/truffle-analyze#33]

**Comment by daniyarchambylov** [comment]
I'm not really sure what you mean by `Update package.json for minimum nodejs version`. Node version  doesn't mention in package.json. Perhaps we  can update Readme file and mention minimum node.js version required to run  truffle-analyze successfully.

**Comment by rocky** [comment]
I just did a google search: https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json
