### ISSUE TITLE
Handle multiple contracts more gracefully.

### ISSUE THREAD

**Issue by rocky** [ConsenSys/truffle-analyze#9]
This will need some coordination with the Mythril Platform API. 

Right now we use the first contract found in the truffle build/contracts/xxx.json file. 
UEscaping the JSON source text right now just handles \\n -> \n. Do we need to do other kinds of \\ escapes.

**Comment by daniyarchambylov** [comment]
@rocky  I've opened PR #34, please look it.
With these changes truffle analyze can collect reports for multiple smart contrast from Mythril Platform API concurrently and show the results on stdout upon completion.
I strongly believe it is a good improvement to what truffle-analyze can do right now.
We can use this approach to handle analyze smart contracts until Mythril Platform API will be able to handle that by itself
